### PR TITLE
Fix missing Embed\Utils import in OembedService.php

### PR DESCRIPTION
**Pull request by juban**
Sorry for this, but there was a missing import in my previous pull request preventing the fix from working.

### CODE REVIEW

**Review by reganlawton — APPROVED** [review]

**Comment by reganlawton** [comment]
@juban  Please see [release v1.3.16](https://github.com/wrav/oembed/releases/tag/1.3.16)

**Comment by juban** [comment]
Thanks again for the release @reganlawton 
BTW, I think the fix should probably also be merged into the v2 branch.

**Comment by juban** [comment]
@reganlawton Also, looks like the release didn't make it to packagist for some reason.

**Comment by reganlawton** [comment]
ARGH! We didn't update the composer.json version I'll update this and create a release v1.3.17

**Comment by reganlawton** [comment]
@juban see https://packagist.org/packages/wrav/oembed#1.3.17

Also v2 branch?

**Comment by juban** [comment]
Thank you for the release, it's ok on Packagist now. Indeed, I did not change the composer.json file as I thought you would like to handle that on your end and as there was conflicts due to v2 in the main branch.
And yes, indeed, the fix in 1.3.17 should be also merged into the v2 branch as the missing import is also present here.

**Comment by reganlawton** [comment]
Hmm I'll look into it we can't merge branched really anymore easily cos v2.X is has breaking changes and might not be the same but I'll look at adding it over

**Comment by juban** [comment]
@reganlawton I've sent you a new PR to fix the issue in the v2 version : https://github.com/wrav/oembed/pull/115

**Pull request merged**
